import { Geist, Geist_Mono, Geologica } from "next/font/google";
import "./globals.css";

// Import Geologica
const geologica = Geologica({
  subsets: ["latin"],
  variable: "--font-geologica",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // optional: choose weights you want
});

// (You can remove Geist if you don’t need it anymore)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geologica.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
